name: Mocean One
favicon: null
layout_spectrum: 0.69022
typography_spectrum: 0.52766
title: 'Demystifying the Worlds Ocean '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2e9f2'
    - '#50889d'
    - '#85b8a1'
    - '#aacbf3'
    - '#2c455b'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
