name: Mocean One
favicon: null
layout_spectrum: 0.46656
typography_spectrum: 0.57046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6875
  lightness: 0.04718157020397484
  saturation: 0.8481098453048617
  rhythmicContrast: 0.23353470372967422
purpose: []
