name: Mocean One
favicon: null
layout_spectrum: 0.84595
typography_spectrum: 0.12766
title: 'Demystifying the Worlds Ocean '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#154970'
    - '#388caf'
    - '#257395'
    - '#42a6b3'
    - '#65c7d2'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
