name: Mocean One
favicon: null
layout_spectrum: 0.1966
typography_spectrum: 0.52766
title: 'Demystifying the Worlds Ocean '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2063aa'
    - '#81bbe0'
    - '#ededed'
    - '#bcb401'
    - '#c1683e'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
