name: Mocean One
favicon: null
layout_spectrum: 0.28954
typography_spectrum: 0.57046
title: 'Demystifying the Worlds Ocean '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8481098453048617
  rhythmicContrast: 0.75
purpose: []
